### ISSUE TITLE
TLS/SSL certificate issue when using deploy guide link

### ISSUE THREAD

**Issue by rib3** [GitbookIO/nuts#66] opened 2016-05-05 16:36 UTC
https://github.com/GitbookIO/nuts/blame/master/README.md#L36

link: https://nuts.gitbook.com/deploy.html

* Cert is wildcard for `*.gitbook.io` (vs `.com`)
  * `nuts.gitbook.io` does not have a DNS entry
* Non-TLS link does work: http://nuts.gitbook.com/deploy.html

**Comment by AaronO** [comment] 2016-05-09 13:15
@rib3 Caused by a DNS misconfiguration, should be fixed now. Might take some time for DNS settings to propagate.

Thanks for pointing this out !

**Closed by AaronO** 2016-05-09 13:15 UTC
